# Generated by Django 4.2.6 on 2023-10-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(default='Раздел', max_length=40)),
                ('rus_name', models.CharField(default='Слово', max_length=40)),
                ('eng_name', models.CharField(default='Word', max_length=40)),
            ],
        ),
    ]
