# Generated by Django 4.2.6 on 2023-10-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_modelcatswords_modelwords_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelwords',
            name='categorie',
        ),
    ]
